In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker
plt.rcParams['figure.figsize'] = [20,15]
import seaborn as sns
sns.set()
sns.set_palette('bright')

In [2]:
df = pd.read_csv('All_CAMCAR_Latest_Cases_Deaths_Recovered_Active.csv', index_col=0)

In [3]:
df

                     Cases  Deaths  Recovered  Active  New Cases
Country/Region
Dominican Republic    3755     196        215    3344        141
Panama                3751     103         75    3573        177
Cuba                   862      27        171     664         48
Costa Rica             642       4         74     564         16
Honduras               426      35          9     382          7
Guatemala              196       5         19     172         16
El Salvador            164       6         33     125          5
Jamaica                143       5         21     117         18
Trinidad and Tobago    114       8         20      86          0
Aruba                   95       2         39      54          2
French Guiana           86       0         51      35          0
Barbados                75       5         15      55          2
Cayman Islands          60       1          6      53          6
Sint Maarten            57       9         12      36          4
Bahamas                 53       8          6      39          4
Haiti                   41       3          0      38          0
St Martin               35       2         13      20          0
Antigua and Barbuda     23       3          3      17          0
Saint Lucia             15       0         11       4          0
Curacao                 14       1         10       3          0
Nicaragua                9       1          4       4          0

In [4]:
data = df.copy()

In [5]:
data['Mortality Ratio'] = data['Deaths']/data['Cases']

In [6]:
data['Mortality pct'] = data['Mortality Ratio']*100

In [7]:
data

,Cases,Deaths,Recovered,Active,New Cases,Mortality Ratio,Mortality pct
Country/Region,,,,,,,
Dominican Republic,3755,196,215,3344,141,0.052197,5.219707
Panama,3751,103,75,3573,177,0.027459,2.745934
Cuba,862,27,171,664,48,0.031323,3.132251
Costa Rica,642,4,74,564,16,0.006231,0.623053
Honduras,426,35,9,382,7,0.082160,8.215962
Guatemala,196,5,19,172,16,0.025510,2.551020
El Salvador,164,6,33,125,5,0.036585,3.658537
Jamaica,143,5,21,117,18,0.034965,3.496503
Trinidad and Tobago,114,8,20,86,0,0.070175,7.017544
Aruba,95,2,39,54,2,0.021053,2.105263
French Guiana,86,0,51,35,0,0.000000,0.000000
Barbados,75,5,15,55,2,0.066667,6.666667
Cayman Islands,60,1,6,53,6,0.016667,1.666667
Sint Maarten,57,9,12,36,4,0.157895,15.789474
Bahamas,53,8,6,39,4,0.150943,15.094340
Haiti,41,3,0,38,0,0.073171,7.317073
St Martin,35,2,13,20,0,0.057143,5.714286
Antigua and Barbuda,23,3,3,17,0,0.130435,13.043478
Saint Lucia,15,0,11,4,0,0.000000,0.000000
Curacao,14,1,10,3,0,0.071429,7.142857
Nicaragua,9,1,4,4,0,0.111111,11.111111

In [8]:
pops = [11108011, 4291013, 11495023, 5044015, 9721007, 17907008, 6480013, 2911015, 1376715, 106521, 297083, 287425, 65565, 42777, 405714, 11374286, 38531, 97765, 181214, 163527, 6416009]

In [9]:
data['Population'] = pops
data

,Cases,Deaths,Recovered,Active,New Cases,Mortality Ratio,Mortality pct,Population
Country/Region,,,,,,,,
Dominican Republic,3755,196,215,3344,141,0.052197,5.219707,11108011
Panama,3751,103,75,3573,177,0.027459,2.745934,4291013
Cuba,862,27,171,664,48,0.031323,3.132251,11495023
Costa Rica,642,4,74,564,16,0.006231,0.623053,5044015
Honduras,426,35,9,382,7,0.082160,8.215962,9721007
Guatemala,196,5,19,172,16,0.025510,2.551020,17907008
El Salvador,164,6,33,125,5,0.036585,3.658537,6480013
Jamaica,143,5,21,117,18,0.034965,3.496503,2911015
Trinidad and Tobago,114,8,20,86,0,0.070175,7.017544,1376715
Aruba,95,2,39,54,2,0.021053,2.105263,106521
French Guiana,86,0,51,35,0,0.000000,0.000000,297083
Barbados,75,5,15,55,2,0.066667,6.666667,287425
Cayman Islands,60,1,6,53,6,0.016667,1.666667,65565
Sint Maarten,57,9,12,36,4,0.157895,15.789474,42777
Bahamas,53,8,6,39,4,0.150943,15.094340,405714
Haiti,41,3,0,38,0,0.073171,7.317073,11374286
St Martin,35,2,13,20,0,0.057143,5.714286,38531
Antigua and Barbuda,23,3,3,17,0,0.130435,13.043478,97765
Saint Lucia,15,0,11,4,0,0.000000,0.000000,181214
Curacao,14,1,10,3,0,0.071429,7.142857,163527
Nicaragua,9,1,4,4,0,0.111111,11.111111,6416009

In [10]:
data.columns.values

array(['Cases', 'Deaths', 'Recovered', 'Active', 'New Cases',
       'Mortality Ratio', 'Mortality pct', 'Population'], dtype=object)

##### Rate of infection 

Defined as: $$\frac{Confirmed}{Population/100000}$$

In [11]:
data['Rate of Infection'] = data['Cases']/(data['Population']/100000)

In [12]:
data

,Cases,Deaths,Recovered,Active,New Cases,Mortality Ratio,Mortality pct,Population,Rate of Infection
Country/Region,,,,,,,,,
Dominican Republic,3755,196,215,3344,141,0.052197,5.219707,11108011,33.804432
Panama,3751,103,75,3573,177,0.027459,2.745934,4291013,87.415256
Cuba,862,27,171,664,48,0.031323,3.132251,11495023,7.498898
Costa Rica,642,4,74,564,16,0.006231,0.623053,5044015,12.727956
Honduras,426,35,9,382,7,0.082160,8.215962,9721007,4.382262
Guatemala,196,5,19,172,16,0.025510,2.551020,17907008,1.094544
El Salvador,164,6,33,125,5,0.036585,3.658537,6480013,2.530859
Jamaica,143,5,21,117,18,0.034965,3.496503,2911015,4.912376
Trinidad and Tobago,114,8,20,86,0,0.070175,7.017544,1376715,8.280581
Aruba,95,2,39,54,2,0.021053,2.105263,106521,89.184292
French Guiana,86,0,51,35,0,0.000000,0.000000,297083,28.948139
Barbados,75,5,15,55,2,0.066667,6.666667,287425,26.093764
Cayman Islands,60,1,6,53,6,0.016667,1.666667,65565,91.512240
Sint Maarten,57,9,12,36,4,0.157895,15.789474,42777,133.249176
Bahamas,53,8,6,39,4,0.150943,15.094340,405714,13.063389
Haiti,41,3,0,38,0,0.073171,7.317073,11374286,0.360462
St Martin,35,2,13,20,0,0.057143,5.714286,38531,90.835950
Antigua and Barbuda,23,3,3,17,0,0.130435,13.043478,97765,23.525802
Saint Lucia,15,0,11,4,0,0.000000,0.000000,181214,8.277506
Curacao,14,1,10,3,0,0.071429,7.142857,163527,8.561277
Nicaragua,9,1,4,4,0,0.111111,11.111111,6416009,0.140274

#### Daily Incidence pct

$$\frac{New Cases}{Confirmed}*100$$

In [13]:
data['Daily Incidence pct'] = data['New Cases']/data['Cases']*100
data

,Cases,Deaths,Recovered,Active,New Cases,Mortality Ratio,Mortality pct,Population,Rate of Infection,Daily Incidence pct
Country/Region,,,,,,,,,,
Dominican Republic,3755,196,215,3344,141,0.052197,5.219707,11108011,33.804432,3.754993
Panama,3751,103,75,3573,177,0.027459,2.745934,4291013,87.415256,4.718742
Cuba,862,27,171,664,48,0.031323,3.132251,11495023,7.498898,5.568445
Costa Rica,642,4,74,564,16,0.006231,0.623053,5044015,12.727956,2.492212
Honduras,426,35,9,382,7,0.082160,8.215962,9721007,4.382262,1.643192
Guatemala,196,5,19,172,16,0.025510,2.551020,17907008,1.094544,8.163265
El Salvador,164,6,33,125,5,0.036585,3.658537,6480013,2.530859,3.048780
Jamaica,143,5,21,117,18,0.034965,3.496503,2911015,4.912376,12.587413
Trinidad and Tobago,114,8,20,86,0,0.070175,7.017544,1376715,8.280581,0.000000
Aruba,95,2,39,54,2,0.021053,2.105263,106521,89.184292,2.105263
French Guiana,86,0,51,35,0,0.000000,0.000000,297083,28.948139,0.000000
Barbados,75,5,15,55,2,0.066667,6.666667,287425,26.093764,2.666667
Cayman Islands,60,1,6,53,6,0.016667,1.666667,65565,91.512240,10.000000
Sint Maarten,57,9,12,36,4,0.157895,15.789474,42777,133.249176,7.017544
Bahamas,53,8,6,39,4,0.150943,15.094340,405714,13.063389,7.547170
Haiti,41,3,0,38,0,0.073171,7.317073,11374286,0.360462,0.000000
St Martin,35,2,13,20,0,0.057143,5.714286,38531,90.835950,0.000000
Antigua and Barbuda,23,3,3,17,0,0.130435,13.043478,97765,23.525802,0.000000
Saint Lucia,15,0,11,4,0,0.000000,0.000000,181214,8.277506,0.000000
Curacao,14,1,10,3,0,0.071429,7.142857,163527,8.561277,0.000000
Nicaragua,9,1,4,4,0,0.111111,11.111111,6416009,0.140274,0.000000

In [14]:
data.columns.values

array(['Cases', 'Deaths', 'Recovered', 'Active', 'New Cases',
       'Mortality Ratio', 'Mortality pct', 'Population',
       'Rate of Infection', 'Daily Incidence pct'], dtype=object)

In [15]:
cols = ['Population', 'Cases', 'Deaths', 'Recovered', 'Active', 'New Cases',
       'Mortality Ratio', 'Mortality pct', 
       'Rate of Infection', 'Daily Incidence pct']

In [16]:
temp = data[cols]
temp

,Population,Cases,Deaths,Recovered,Active,New Cases,Mortality Ratio,Mortality pct,Rate of Infection,Daily Incidence pct
Country/Region,,,,,,,,,,
Dominican Republic,11108011,3755,196,215,3344,141,0.052197,5.219707,33.804432,3.754993
Panama,4291013,3751,103,75,3573,177,0.027459,2.745934,87.415256,4.718742
Cuba,11495023,862,27,171,664,48,0.031323,3.132251,7.498898,5.568445
Costa Rica,5044015,642,4,74,564,16,0.006231,0.623053,12.727956,2.492212
Honduras,9721007,426,35,9,382,7,0.082160,8.215962,4.382262,1.643192
Guatemala,17907008,196,5,19,172,16,0.025510,2.551020,1.094544,8.163265
El Salvador,6480013,164,6,33,125,5,0.036585,3.658537,2.530859,3.048780
Jamaica,2911015,143,5,21,117,18,0.034965,3.496503,4.912376,12.587413
Trinidad and Tobago,1376715,114,8,20,86,0,0.070175,7.017544,8.280581,0.000000
Aruba,106521,95,2,39,54,2,0.021053,2.105263,89.184292,2.105263
French Guiana,297083,86,0,51,35,0,0.000000,0.000000,28.948139,0.000000
Barbados,287425,75,5,15,55,2,0.066667,6.666667,26.093764,2.666667
Cayman Islands,65565,60,1,6,53,6,0.016667,1.666667,91.512240,10.000000
Sint Maarten,42777,57,9,12,36,4,0.157895,15.789474,133.249176,7.017544
Bahamas,405714,53,8,6,39,4,0.150943,15.094340,13.063389,7.547170
Haiti,11374286,41,3,0,38,0,0.073171,7.317073,0.360462,0.000000
St Martin,38531,35,2,13,20,0,0.057143,5.714286,90.835950,0.000000
Antigua and Barbuda,97765,23,3,3,17,0,0.130435,13.043478,23.525802,0.000000
Saint Lucia,181214,15,0,11,4,0,0.000000,0.000000,8.277506,0.000000
Curacao,163527,14,1,10,3,0,0.071429,7.142857,8.561277,0.000000
Nicaragua,6416009,9,1,4,4,0,0.111111,11.111111,0.140274,0.000000

In [17]:
temp.drop(['French Guiana', 'Cayman Islands', 'Sint Maarten', 'Haiti', 'St Martin', 'Antigua and Barbuda'], axis=0, inplace=True)

/home/andres/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py:3997: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  errors=errors,

In [18]:
result = temp.copy()

In [19]:
result

,Population,Cases,Deaths,Recovered,Active,New Cases,Mortality Ratio,Mortality pct,Rate of Infection,Daily Incidence pct
Country/Region,,,,,,,,,,
Dominican Republic,11108011,3755,196,215,3344,141,0.052197,5.219707,33.804432,3.754993
Panama,4291013,3751,103,75,3573,177,0.027459,2.745934,87.415256,4.718742
Cuba,11495023,862,27,171,664,48,0.031323,3.132251,7.498898,5.568445
Costa Rica,5044015,642,4,74,564,16,0.006231,0.623053,12.727956,2.492212
Honduras,9721007,426,35,9,382,7,0.082160,8.215962,4.382262,1.643192
Guatemala,17907008,196,5,19,172,16,0.025510,2.551020,1.094544,8.163265
El Salvador,6480013,164,6,33,125,5,0.036585,3.658537,2.530859,3.048780
Jamaica,2911015,143,5,21,117,18,0.034965,3.496503,4.912376,12.587413
Trinidad and Tobago,1376715,114,8,20,86,0,0.070175,7.017544,8.280581,0.000000
Aruba,106521,95,2,39,54,2,0.021053,2.105263,89.184292,2.105263
Barbados,287425,75,5,15,55,2,0.066667,6.666667,26.093764,2.666667
Bahamas,405714,53,8,6,39,4,0.150943,15.094340,13.063389,7.547170
Saint Lucia,181214,15,0,11,4,0,0.000000,0.000000,8.277506,0.000000
Curacao,163527,14,1,10,3,0,0.071429,7.142857,8.561277,0.000000
Nicaragua,6416009,9,1,4,4,0,0.111111,11.111111,0.140274,0.000000

In [22]:
result = result.round(2)
result.to_csv('CAMCAR_COVID_Cases.csv')